on: [workflow_dispatch]

name: Create Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Build Project
      run: ./mvnw -B package --file pom.xml

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Extract Tag Name
      id: extract_tag
      run: echo "release/${{ github.ref }}"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false

