on: [workflow_dispatch]

name: Create Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Build Project
      run: ./mvnw -B package --file pom.xml

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: java-project
        path: target/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Extract Tag Name
      id: extract_tag
      run: echo "release/${{ github.ref }}"

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: java-project

    - name: Create Release Tag
      id: create_tag
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.TOKEN }}
        tag_prefix: v

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ steps.create_tag.outputs.new_tag }}
        release_name: Release ${{ steps.create_tag.outputs.new_tag }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: hello/target/*.jar
        asset_name: hello.jar
        asset_content_type: application/java-archive
